
var webp_dec = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(webp_dec) {
  webp_dec = webp_dec || {};


var e;e||(e=typeof webp_dec !== 'undefined' ? webp_dec : {});var aa;e.ready=new Promise(function(a){aa=a});var r={},x;for(x in e)e.hasOwnProperty(x)&&(r[x]=e[x]);var ba=!1,y=!1,ca=!1,da=!1;ba="object"===typeof window;y="function"===typeof importScripts;ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!ba&&!ca&&!y;var z="",ea,A,ha,ia;
if(ca)z=y?require("path").dirname(z)+"/":__dirname+"/",ea=function(a,b){ha||(ha=require("fs"));ia||(ia=require("path"));a=ia.normalize(a);return ha.readFileSync(a,b?null:"utf8")},A=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||D("Assertion failed: undefined");return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",D),e.inspect=function(){return"[Emscripten Module object]"};
else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),A=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||D("Assertion failed: undefined");return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||y)y?z=self.location.href:document.currentScript&&(z=document.currentScript.src),_scriptDir&&
(z=_scriptDir),0!==z.indexOf("blob:")?z=z.substr(0,z.lastIndexOf("/")+1):z="",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},y&&(A=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ja=e.print||console.log.bind(console),E=e.printErr||console.warn.bind(console);for(x in r)r.hasOwnProperty(x)&&(e[x]=r[x]);r=null;var F;e.wasmBinary&&(F=e.wasmBinary);var noExitRuntime;
e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&E("no native wasm support detected");var G,ka=new WebAssembly.Table({initial:138,maximum:138,element:"anyfunc"}),la=!1,ma="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(a,b,c){var d=H;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var p=a.charCodeAt(++f);g=65536+((g&1023)<<10)|p&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function pa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&qa[c];)++c;c<<=1;if(32<c-a&&oa)return oa.decode(H.subarray(a,c));c=0;for(d="";;){var f=I[a+2*c>>1];if(0==f||c==b/2)return d;++c;d+=String.fromCharCode(f)}}function ra(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)I[b>>1]=a.charCodeAt(f),b+=2;I[b>>1]=0;return b-d}function sa(a){return 2*a.length}
function ta(a,b){for(var c=0,d="";!(c>=b/4);){var f=J[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function ua(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var p=a.charCodeAt(++f);g=65536+((g&1023)<<10)|p&1023}J[b>>2]=g;b+=4;if(b+4>c)break}J[b>>2]=0;return b-d}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var K,wa,H,I,qa,J,L,xa,ya;function za(a){K=a;e.HEAP8=wa=new Int8Array(a);e.HEAP16=I=new Int16Array(a);e.HEAP32=J=new Int32Array(a);e.HEAPU8=H=new Uint8Array(a);e.HEAPU16=qa=new Uint16Array(a);e.HEAPU32=L=new Uint32Array(a);e.HEAPF32=xa=new Float32Array(a);e.HEAPF64=ya=new Float64Array(a)}var Aa=e.INITIAL_MEMORY||16777216;
e.wasmMemory?G=e.wasmMemory:G=new WebAssembly.Memory({initial:Aa/65536,maximum:32768});G&&(K=G.buffer);Aa=K.byteLength;za(K);J[3336]=5256384;function Ba(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.la;"number"===typeof c?void 0===b.da?e.dynCall_v(c):e.dynCall_vi(c,b.da):c(void 0===b.da?null:b.da)}}}var Ca=[],Da=[],Ea=[],Fa=[];function Ga(){var a=e.preRun.shift();Ca.unshift(a)}var M=0,Ha=null,N=null;e.preloadedImages={};e.preloadedAudios={};
function D(a){if(e.onAbort)e.onAbort(a);ja(a);E(a);la=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ia(a){var b=O;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ja(){return Ia("data:application/octet-stream;base64,")}var O="webp_dec.wasm";if(!Ja()){var Ka=O;O=e.locateFile?e.locateFile(Ka,z):z+Ka}
function La(){try{if(F)return new Uint8Array(F);if(A)return A(O);throw"both async and sync fetching of the wasm failed";}catch(a){D(a)}}function Ma(){return F||!ba&&!y||"function"!==typeof fetch||Ia("file://")?new Promise(function(a){a(La())}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return La()})}Da.push({la:function(){Na()}});function Oa(){return 0<Oa.Y}
function Pa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Qa=void 0;function P(a){for(var b="";H[a];)b+=Qa[H[a++]];return b}var Q={},R={},Ra={};function Sa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Ta(a,b){a=Sa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Ua(a){var b=Error,c=Ta(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Va=void 0;function S(a){throw new Va(a);}var Wa=void 0;function Xa(a){throw new Wa(a);}function Ya(a,b,c){function d(k){k=c(k);k.length!==a.length&&Xa("Mismatched type converter count");for(var h=0;h<a.length;++h)T(a[h],k[h])}a.forEach(function(k){Ra[k]=b});var f=Array(b.length),g=[],p=0;b.forEach(function(k,h){R.hasOwnProperty(k)?f[h]=R[k]:(g.push(k),Q.hasOwnProperty(k)||(Q[k]=[]),Q[k].push(function(){f[h]=R[k];++p;p===g.length&&d(f)}))});0===g.length&&d(f)}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(R.hasOwnProperty(a)){if(c.oa)return;S("Cannot register type '"+d+"' twice")}R[a]=b;delete Ra[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(function(f){f()}))}function Za(a){return{count:a.count,X:a.X,Z:a.Z,M:a.M,O:a.O,P:a.P,R:a.R}}
function $a(a){S(a.L.O.N.name+" instance already deleted")}var ab=!1;function bb(){}function cb(a){--a.count.value;0===a.count.value&&(a.P?a.R.W(a.P):a.O.N.W(a.M))}function db(a){if("undefined"===typeof FinalizationGroup)return db=function(b){return b},a;ab=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.M?cb(c):console.warn("object already deleted: "+c.M)});db=function(b){ab.register(b,b.L,b.L);return b};bb=function(b){ab.unregister(b.L)};return db(a)}
var eb=void 0,fb=[];function gb(){for(;fb.length;){var a=fb.pop();a.L.X=!1;a["delete"]()}}function U(){}var hb={};function ib(a,b){var c=e;if(void 0===c[a].T){var d=c[a];c[a]=function(){c[a].T.hasOwnProperty(arguments.length)||S("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].T+")!");return c[a].T[arguments.length].apply(this,arguments)};c[a].T=[];c[a].T[d.ia]=d}}
function jb(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].T&&void 0!==e[a].T[c])&&S("Cannot register public name '"+a+"' twice"),ib(a,a),e.hasOwnProperty(c)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].T[c]=b):(e[a]=b,void 0!==c&&(e[a].ua=c))}function kb(a,b,c,d,f,g,p,k){this.name=a;this.constructor=b;this.V=c;this.W=d;this.S=f;this.ma=g;this.$=p;this.ka=k}
function lb(a,b,c){for(;b!==c;)b.$||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.$(a),b=b.S;return a}function mb(a,b){if(null===b)return this.ea&&S("null is not a valid "+this.name),0;b.L||S('Cannot pass "'+V(b)+'" as a '+this.name);b.L.M||S("Cannot pass deleted object as a pointer of type "+this.name);return lb(b.L.M,b.L.O.N,this.N)}
function nb(a,b){if(null===b){this.ea&&S("null is not a valid "+this.name);if(this.ba){var c=this.qa();null!==a&&a.push(this.W,c);return c}return 0}b.L||S('Cannot pass "'+V(b)+'" as a '+this.name);b.L.M||S("Cannot pass deleted object as a pointer of type "+this.name);!this.aa&&b.L.O.aa&&S("Cannot convert argument of type "+(b.L.R?b.L.R.name:b.L.O.name)+" to parameter type "+this.name);c=lb(b.L.M,b.L.O.N,this.N);if(this.ba)switch(void 0===b.L.P&&S("Passing raw pointer to smart pointer is illegal"),
this.sa){case 0:b.L.R===this?c=b.L.P:S("Cannot convert argument of type "+(b.L.R?b.L.R.name:b.L.O.name)+" to parameter type "+this.name);break;case 1:c=b.L.P;break;case 2:if(b.L.R===this)c=b.L.P;else{var d=b.clone();c=this.ra(c,ob(function(){d["delete"]()}));null!==a&&a.push(this.W,c)}break;default:S("Unsupporting sharing policy")}return c}
function pb(a,b){if(null===b)return this.ea&&S("null is not a valid "+this.name),0;b.L||S('Cannot pass "'+V(b)+'" as a '+this.name);b.L.M||S("Cannot pass deleted object as a pointer of type "+this.name);b.L.O.aa&&S("Cannot convert argument of type "+b.L.O.name+" to parameter type "+this.name);return lb(b.L.M,b.L.O.N,this.N)}function rb(a){return this.fromWireType(L[a>>2])}function sb(a,b,c){if(b===c)return a;if(void 0===c.S)return null;a=sb(a,b,c.S);return null===a?null:c.ka(a)}var tb={};
function ub(a,b){for(void 0===b&&S("ptr should not be undefined");a.S;)b=a.$(b),a=a.S;return tb[b]}function vb(a,b){b.O&&b.M||Xa("makeClassHandle requires ptr and ptrType");!!b.R!==!!b.P&&Xa("Both smartPtrType and smartPtr must be specified");b.count={value:1};return db(Object.create(a,{L:{value:b}}))}function W(a,b,c,d){this.name=a;this.N=b;this.ea=c;this.aa=d;this.ba=!1;this.W=this.ra=this.qa=this.ha=this.sa=this.pa=void 0;void 0!==b.S?this.toWireType=nb:(this.toWireType=d?mb:pb,this.U=null)}
function wb(a,b,c){e.hasOwnProperty(a)||Xa("Replacing nonexistant public symbol");void 0!==e[a].T&&void 0!==c?e[a].T[c]=b:(e[a]=b,e[a].ia=c)}
function X(a,b){a=P(a);var c=e["dynCall_"+a];for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var xb=void 0;function yb(a){a=zb(a);var b=P(a);Y(a);return b}
function Ab(a,b){function c(g){f[g]||R[g]||(Ra[g]?Ra[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new xb(a+": "+d.map(yb).join([", "]));}function Bb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Cb(a,b,c){a instanceof Object||S(c+' with invalid "this": '+a);a instanceof b.N.constructor||S(c+' incompatible with "this" of type '+a.constructor.name);a.L.M||S("cannot call emscripten binding method "+c+" on deleted object");return lb(a.L.M,a.L.O.N,b.N)}
var Db=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Eb(a){4<a&&0===--Z[a].fa&&(Z[a]=void 0,Db.push(a))}function ob(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Db.length?Db.pop():Z.length;Z[b]={fa:1,value:a};return b}}function V(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Fb(a,b){switch(b){case 2:return function(c){return this.fromWireType(xa[c>>2])};case 3:return function(c){return this.fromWireType(ya[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Gb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ta(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Hb(a,b){for(var c=[],d=0;d<a;d++)c.push(J[(b>>2)+d]);return c}function Ib(a,b,c){switch(b){case 0:return c?function(d){return wa[d]}:function(d){return H[d]};case 1:return c?function(d){return I[d>>1]}:function(d){return qa[d>>1]};case 2:return c?function(d){return J[d>>2]}:function(d){return L[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var Jb=Array(256),Kb=0;256>Kb;++Kb)Jb[Kb]=String.fromCharCode(Kb);Qa=Jb;Va=e.BindingError=Ua("BindingError");
Wa=e.InternalError=Ua("InternalError");U.prototype.isAliasOf=function(a){if(!(this instanceof U&&a instanceof U))return!1;var b=this.L.O.N,c=this.L.M,d=a.L.O.N;for(a=a.L.M;b.S;)c=b.$(c),b=b.S;for(;d.S;)a=d.$(a),d=d.S;return b===d&&c===a};U.prototype.clone=function(){this.L.M||$a(this);if(this.L.Z)return this.L.count.value+=1,this;var a=db(Object.create(Object.getPrototypeOf(this),{L:{value:Za(this.L)}}));a.L.count.value+=1;a.L.X=!1;return a};
U.prototype["delete"]=function(){this.L.M||$a(this);this.L.X&&!this.L.Z&&S("Object already scheduled for deletion");bb(this);cb(this.L);this.L.Z||(this.L.P=void 0,this.L.M=void 0)};U.prototype.isDeleted=function(){return!this.L.M};U.prototype.deleteLater=function(){this.L.M||$a(this);this.L.X&&!this.L.Z&&S("Object already scheduled for deletion");fb.push(this);1===fb.length&&eb&&eb(gb);this.L.X=!0;return this};W.prototype.na=function(a){this.ha&&(a=this.ha(a));return a};
W.prototype.ga=function(a){this.W&&this.W(a)};W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=rb;W.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
W.prototype.fromWireType=function(a){function b(){return this.ba?vb(this.N.V,{O:this.pa,M:c,R:this,P:a}):vb(this.N.V,{O:this,M:a})}var c=this.na(a);if(!c)return this.ga(a),null;var d=ub(this.N,c);if(void 0!==d){if(0===d.L.count.value)return d.L.M=c,d.L.P=a,d.clone();d=d.clone();this.ga(a);return d}d=this.N.ma(c);d=hb[d];if(!d)return b.call(this);d=this.aa?d.ja:d.pointerType;var f=sb(c,this.N,d.N);return null===f?b.call(this):this.ba?vb(d.N.V,{O:d,M:f,R:this,P:a}):vb(d.N.V,{O:d,M:f})};
e.getInheritedInstanceCount=function(){return Object.keys(tb).length};e.getLiveInheritedInstances=function(){var a=[],b;for(b in tb)tb.hasOwnProperty(b)&&a.push(tb[b]);return a};e.flushPendingDeletes=gb;e.setDelayFunction=function(a){eb=a;fb.length&&eb&&eb(gb)};xb=e.UnboundTypeError=Ua("UnboundTypeError");e.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
var Mb={n:function(a){return Lb(a)},m:function(a){"uncaught_exception"in Oa?Oa.Y++:Oa.Y=1;throw a;},k:function(a,b,c,d,f){var g=Pa(c);b=P(b);T(a,{name:b,fromWireType:function(p){return!!p},toWireType:function(p,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(p){if(1===c)var k=wa;else if(2===c)k=I;else if(4===c)k=J;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[p>>g])},U:null})},o:function(a,b,c,d,f,g,p,k,h,q,l,n,t){l=P(l);g=X(f,g);k&&(k=X(p,k));
q&&(q=X(h,q));t=X(n,t);var u=Sa(l);jb(u,function(){Ab("Cannot construct "+l+" due to unbound types",[d])});Ya([a,b,c],d?[d]:[],function(m){m=m[0];if(d){var C=m.N;var v=C.V}else v=U.prototype;m=Ta(u,function(){if(Object.getPrototypeOf(this)!==w)throw new Va("Use 'new' to construct "+l);if(void 0===B.Y)throw new Va(l+" has no accessible constructor");var qb=B.Y[arguments.length];if(void 0===qb)throw new Va("Tried to invoke ctor of "+l+" with invalid number of parameters ("+arguments.length+") - expected ("+
Object.keys(B.Y).toString()+") parameters instead!");return qb.apply(this,arguments)});var w=Object.create(v,{constructor:{value:m}});m.prototype=w;var B=new kb(l,m,w,t,C,g,k,q);C=new W(l,B,!0,!1);v=new W(l+"*",B,!1,!1);var fa=new W(l+" const*",B,!1,!0);hb[a]={pointerType:v,ja:fa};wb(u,m);return[C,v,fa]})},e:function(a,b,c,d,f,g,p,k,h,q){b=P(b);f=X(d,f);Ya([],[a],function(l){l=l[0];var n=l.name+"."+b,t={get:function(){Ab("Cannot access "+n+" due to unbound types",[c,p])},enumerable:!0,configurable:!0};
h?t.set=function(){Ab("Cannot access "+n+" due to unbound types",[c,p])}:t.set=function(){S(n+" is a read-only property")};Object.defineProperty(l.N.V,b,t);Ya([],h?[c,p]:[c],function(u){var m=u[0],C={get:function(){var w=Cb(this,l,n+" getter");return m.fromWireType(f(g,w))},enumerable:!0};if(h){h=X(k,h);var v=u[1];C.set=function(w){var B=Cb(this,l,n+" setter"),fa=[];h(q,B,v.toWireType(fa,w));Bb(fa)}}Object.defineProperty(l.N.V,b,C);return[]});return[]})},r:function(a,b){b=P(b);T(a,{name:b,fromWireType:function(c){var d=
Z[c].value;Eb(c);return d},toWireType:function(c,d){return ob(d)},argPackAdvance:8,readValueFromPointer:rb,U:null})},h:function(a,b,c){c=Pa(c);b=P(b);T(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+V(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Fb(b,c),U:null})},d:function(a,b,c,d,f,g){var p=Hb(b,c);a=P(a);f=X(d,f);jb(a,function(){Ab("Cannot call "+a+" due to unbound types",
p)},b-1);Ya([],p,function(k){var h=[k[0],null].concat(k.slice(1)),q=k=a,l=f,n=h.length;2>n&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var t=null!==h[1]&&!1,u=!1,m=1;m<h.length;++m)if(null!==h[m]&&void 0===h[m].U){u=!0;break}var C="void"!==h[0].name,v="",w="";for(m=0;m<n-2;++m)v+=(0!==m?", ":"")+"arg"+m,w+=(0!==m?", ":"")+"arg"+m+"Wired";q="return function "+Sa(q)+"("+v+") {\nif (arguments.length !== "+(n-2)+") {\nthrowBindingError('function "+q+" called with ' + arguments.length + ' arguments, expected "+
(n-2)+" args!');\n}\n";u&&(q+="var destructors = [];\n");var B=u?"destructors":"null";v="throwBindingError invoker fn runDestructors retType classParam".split(" ");l=[S,l,g,Bb,h[0],h[1]];t&&(q+="var thisWired = classParam.toWireType("+B+", this);\n");for(m=0;m<n-2;++m)q+="var arg"+m+"Wired = argType"+m+".toWireType("+B+", arg"+m+"); // "+h[m+2].name+"\n",v.push("argType"+m),l.push(h[m+2]);t&&(w="thisWired"+(0<w.length?", ":"")+w);q+=(C?"var rv = ":"")+"invoker(fn"+(0<w.length?", ":"")+w+");\n";if(u)q+=
"runDestructors(destructors);\n";else for(m=t?1:2;m<h.length;++m)n=1===m?"thisWired":"arg"+(m-2)+"Wired",null!==h[m].U&&(q+=n+"_dtor("+n+"); // "+h[m].name+"\n",v.push(n+"_dtor"),l.push(h[m].U));C&&(q+="var ret = retType.fromWireType(rv);\nreturn ret;\n");v.push(q+"}\n");h=Gb(v).apply(null,l);wb(k,h,b-1);return[]})},b:function(a,b,c,d,f){function g(q){return q}b=P(b);-1===f&&(f=4294967295);var p=Pa(c);if(0===d){var k=32-8*c;g=function(q){return q<<k>>>k}}var h=-1!=b.indexOf("unsigned");T(a,{name:b,
fromWireType:g,toWireType:function(q,l){if("number"!==typeof l&&"boolean"!==typeof l)throw new TypeError('Cannot convert "'+V(l)+'" to '+this.name);if(l<d||l>f)throw new TypeError('Passing a number "'+V(l)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return h?l>>>0:l|0},argPackAdvance:8,readValueFromPointer:Ib(b,p,0!==d),U:null})},a:function(a,b,c){function d(g){g>>=2;var p=L;return new f(K,p[g+1],p[g])}var f=[Int8Array,Uint8Array,
Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{oa:!0})},i:function(a,b){b=P(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var f=L[d>>2];if(c)for(var g=d+4,p=0;p<=f;++p){var k=d+4+p;if(0==H[k]||p==f){if(g){var h=g;var q=H,l=h+(k-g);for(g=h;q[g]&&!(g>=l);)++g;if(16<g-h&&q.subarray&&ma)h=ma.decode(q.subarray(h,g));else{for(l="";h<g;){var n=q[h++];if(n&128){var t=q[h++]&63;if(192==
(n&224))l+=String.fromCharCode((n&31)<<6|t);else{var u=q[h++]&63;n=224==(n&240)?(n&15)<<12|t<<6|u:(n&7)<<18|t<<12|u<<6|q[h++]&63;65536>n?l+=String.fromCharCode(n):(n-=65536,l+=String.fromCharCode(55296|n>>10,56320|n&1023))}}else l+=String.fromCharCode(n)}h=l}}else h="";if(void 0===m)var m=h;else m+=String.fromCharCode(0),m+=h;g=k+1}}else{m=Array(f);for(p=0;p<f;++p)m[p]=String.fromCharCode(H[d+4+p]);m=m.join("")}Y(d);return m},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));
var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||S("Cannot pass non-string to std::string");var p=(c&&g?function(){for(var q=0,l=0;l<f.length;++l){var n=f.charCodeAt(l);55296<=n&&57343>=n&&(n=65536+((n&1023)<<10)|f.charCodeAt(++l)&1023);127>=n?++q:q=2047>=n?q+2:65535>=n?q+3:q+4}return q}:function(){return f.length})(),k=Lb(4+p+1);L[k>>2]=p;if(c&&g)na(f,k+4,p+1);else if(g)for(g=0;g<p;++g){var h=f.charCodeAt(g);255<h&&(Y(k),S("String has UTF-16 code units that do not fit in 8 bits"));
H[k+4+g]=h}else for(g=0;g<p;++g)H[k+4+g]=f[g];null!==d&&d.push(Y,k);return k},argPackAdvance:8,readValueFromPointer:rb,U:function(d){Y(d)}})},f:function(a,b,c){c=P(c);if(2===b){var d=pa;var f=ra;var g=sa;var p=function(){return qa};var k=1}else 4===b&&(d=ta,f=ua,g=va,p=function(){return L},k=2);T(a,{name:c,fromWireType:function(h){for(var q=L[h>>2],l=p(),n,t=h+4,u=0;u<=q;++u){var m=h+4+u*b;if(0==l[m>>k]||u==q)t=d(t,m-t),void 0===n?n=t:(n+=String.fromCharCode(0),n+=t),t=m+b}Y(h);return n},toWireType:function(h,
q){"string"!==typeof q&&S("Cannot pass non-string to C++ string type "+c);var l=g(q),n=Lb(4+l+b);L[n>>2]=l>>k;f(q,n+4,l+b);null!==h&&h.push(Y,n);return n},argPackAdvance:8,readValueFromPointer:rb,U:function(h){Y(h)}})},l:function(a,b){b=P(b);T(a,{ta:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},g:Eb,s:function(a){4<a&&(Z[a].fa+=1)},j:function(a,b){var c=R[a];void 0===c&&S("_emval_take_value has unknown type "+yb(a));a=c.readValueFromPointer(b);return ob(a)},q:function(){D()},
p:function(a,b,c){H.copyWithin(a,b,b+c)},c:function(a){a>>>=0;var b=H.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{G.grow(Math.min(2147483648,d)-K.byteLength+65535>>>16);za(G.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},memory:G,table:ka};
(function(){function a(f){e.asm=f.exports;M--;e.monitorRunDependencies&&e.monitorRunDependencies(M);0==M&&(null!==Ha&&(clearInterval(Ha),Ha=null),N&&(f=N,N=null,f()))}function b(f){a(f.instance)}function c(f){return Ma().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){E("failed to asynchronously prepare wasm: "+g);D(g)})}var d={a:Mb};M++;e.monitorRunDependencies&&e.monitorRunDependencies(M);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return E("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(F||"function"!==typeof WebAssembly.instantiateStreaming||Ja()||Ia("file://")||"function"!==typeof fetch)return c(b);fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){E("wasm streaming compile failed: "+g);E("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Na=e.___wasm_call_ctors=function(){return(Na=e.___wasm_call_ctors=e.asm.t).apply(null,arguments)},Y=e._free=function(){return(Y=e._free=e.asm.u).apply(null,arguments)},Lb=e._malloc=function(){return(Lb=e._malloc=e.asm.v).apply(null,arguments)},zb=e.___getTypeName=function(){return(zb=e.___getTypeName=e.asm.w).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.x).apply(null,arguments)};
e.dynCall_ii=function(){return(e.dynCall_ii=e.asm.y).apply(null,arguments)};e.dynCall_vi=function(){return(e.dynCall_vi=e.asm.z).apply(null,arguments)};e.dynCall_iii=function(){return(e.dynCall_iii=e.asm.A).apply(null,arguments)};e.dynCall_viii=function(){return(e.dynCall_viii=e.asm.B).apply(null,arguments)};e.dynCall_vii=function(){return(e.dynCall_vii=e.asm.C).apply(null,arguments)};e.dynCall_i=function(){return(e.dynCall_i=e.asm.D).apply(null,arguments)};
e.dynCall_v=function(){return(e.dynCall_v=e.asm.E).apply(null,arguments)};e.dynCall_iiii=function(){return(e.dynCall_iiii=e.asm.F).apply(null,arguments)};e.dynCall_iiiiiii=function(){return(e.dynCall_iiiiiii=e.asm.G).apply(null,arguments)};e.dynCall_viiii=function(){return(e.dynCall_viiii=e.asm.H).apply(null,arguments)};e.dynCall_viiiii=function(){return(e.dynCall_viiiii=e.asm.I).apply(null,arguments)};e.dynCall_viiiiiiiii=function(){return(e.dynCall_viiiiiiiii=e.asm.J).apply(null,arguments)};
e.dynCall_viiiiii=function(){return(e.dynCall_viiiiii=e.asm.K).apply(null,arguments)};var Nb;N=function Ob(){Nb||Pb();Nb||(N=Ob)};
function Pb(){function a(){if(!Nb&&(Nb=!0,e.calledRun=!0,!la)){Ba(Da);Ba(Ea);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Fa.unshift(b)}Ba(Fa)}}if(!(0<M)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ga();Ba(Ca);0<M||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
e.run=Pb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;Pb();


  return webp_dec.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = webp_dec;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return webp_dec; });
    else if (typeof exports === 'object')
      exports["webp_dec"] = webp_dec;
    